"""
dag_tutorial
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="Hello")
def Hello_func():
    message = "Hello"
    print(message)
    return message

@aql.dataframe(task_id="World")
def World_func():
    message = "World"
    print(message)
    return message

default_args={
    "owner": "Takashi Miyauchi,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-12-30", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Takashi Miyauchi": "mailto:hightensan@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/clqq7xk3x017n01p0p69f5l7t/cloud-ide/clqrj9nwy04mc01k9p0n0rq77/clqrja8mc04md01k93jchjp8w",
    },
)
def dag_tutorial():
    Hello = Hello_func()

    World = World_func()

    World << Hello

dag_obj = dag_tutorial()
